#include "pipeline_parts/PipelineUnivariate.cpp"
#include "pipeline_parts/PipelineModeling.cpp"
#include "pipeline_parts/PipelineBivariate.cpp"
#include "pipeline_parts/PipelineReporting.cpp"
#include "pipeline_parts/PipelineRuntime.cpp"
